//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCompiler.AssembleHelp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ac {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ac() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCompiler.AssembleHelp.Ac", typeof(Ac).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anl.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit.
        /// </summary>
        internal static string Bit {
            get {
                return ResourceManager.GetString("Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clr.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cjne.
        /// </summary>
        internal static string CompareAndJumpNotEqual {
            get {
                return ResourceManager.GetString("CompareAndJumpNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpl.
        /// </summary>
        internal static string Complement {
            get {
                return ResourceManager.GetString("Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djnz.
        /// </summary>
        internal static string DecreaseAndJumpNotZero {
            get {
                return ResourceManager.GetString("DecreaseAndJumpNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dec.
        /// </summary>
        internal static string Decrement {
            get {
                return ResourceManager.GetString("Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xch.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xchd.
        /// </summary>
        internal static string ExchangeD {
            get {
                return ResourceManager.GetString("ExchangeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to include.
        /// </summary>
        internal static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inc.
        /// </summary>
        internal static string Increment {
            get {
                return ResourceManager.GetString("Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmp.
        /// </summary>
        internal static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jb.
        /// </summary>
        internal static string JumpBit {
            get {
                return ResourceManager.GetString("JumpBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jc.
        /// </summary>
        internal static string JumpBitCarry {
            get {
                return ResourceManager.GetString("JumpBitCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jc.
        /// </summary>
        internal static string JumpIfCarry {
            get {
                return ResourceManager.GetString("JumpIfCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jnc.
        /// </summary>
        internal static string JumpIfNotCarry {
            get {
                return ResourceManager.GetString("JumpIfNotCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jnz.
        /// </summary>
        internal static string JumpIfNotZero {
            get {
                return ResourceManager.GetString("JumpIfNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jz.
        /// </summary>
        internal static string JumpIfZero {
            get {
                return ResourceManager.GetString("JumpIfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jnb.
        /// </summary>
        internal static string JumpNotBit {
            get {
                return ResourceManager.GetString("JumpNotBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ljmp.
        /// </summary>
        internal static string LongJump {
            get {
                return ResourceManager.GetString("LongJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mov.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movc.
        /// </summary>
        internal static string MoveCarry {
            get {
                return ResourceManager.GetString("MoveCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movx.
        /// </summary>
        internal static string MoveExtended {
            get {
                return ResourceManager.GetString("MoveExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mul.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nop.
        /// </summary>
        internal static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orl.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pop.
        /// </summary>
        internal static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push.
        /// </summary>
        internal static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ret.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rl.
        /// </summary>
        internal static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rlc.
        /// </summary>
        internal static string RotateLeftCarry {
            get {
                return ResourceManager.GetString("RotateLeftCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rr.
        /// </summary>
        internal static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rrc.
        /// </summary>
        internal static string RotateRightCarry {
            get {
                return ResourceManager.GetString("RotateRightCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setb.
        /// </summary>
        internal static string SetBit {
            get {
                return ResourceManager.GetString("SetBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subb.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xrl.
        /// </summary>
        internal static string XOr {
            get {
                return ResourceManager.GetString("XOr", resourceCulture);
            }
        }
    }
}
