using System.Collections.Generic;
using System.Windows.Forms;


namespace MetaTextBox
{
    public class KeyInput
    {
        public KeyInput (Keys key, char? normalChar, char? shiftChar, char? controlAltChar)
        {
            Key = key;
            NormalChar = normalChar;
            ShiftChar = shiftChar;
            ControlAltChar = controlAltChar;
        }

        public Keys Key { get; }
        public char? NormalChar { get; }
        public char? ShiftChar { get; }
        public char? ControlAltChar { get; }

        public char? GetCharacter (bool shift, bool control, bool alt)
        {
            if (!shift && !control && !alt)
                return NormalChar;
            if (shift && !control && !alt)
                return ShiftChar;
            if (!shift && control && alt)
                return ControlAltChar;
            return null;
        }

        public static List<KeyInput> AllKeyInputs = new List<KeyInput>
        {
            new KeyInput (Keys.None, null, null, null),
            new KeyInput (Keys.LButton, null, null, null),
            new KeyInput (Keys.RButton, null, null, null),
            new KeyInput (Keys.Cancel, null, null, null),
            new KeyInput (Keys.MButton, null, null, null),
            new KeyInput (Keys.XButton1, null, null, null),
            new KeyInput (Keys.XButton2, null, null, null),
            new KeyInput (Keys.Back, null, null, null),
            new KeyInput (Keys.Tab, '\t', null, null),
            new KeyInput (Keys.LineFeed, null, null, null),
            new KeyInput (Keys.Clear, null, null, null),
            new KeyInput (Keys.Enter, '\n', '\n', null),
            new KeyInput (Keys.Return, '\n', '\n', null),
            new KeyInput (Keys.ShiftKey, null, null, null),
            new KeyInput (Keys.ControlKey, null, null, null),
            new KeyInput (Keys.Menu, null, null, null),
            new KeyInput (Keys.Pause, null, null, null),
            new KeyInput (Keys.CapsLock, null, null, null),
            new KeyInput (Keys.Capital, null, null, null),
            new KeyInput (Keys.HangulMode, null, null, null),
            new KeyInput (Keys.HanguelMode, null, null, null),
            new KeyInput (Keys.KanaMode, null, null, null),
            new KeyInput (Keys.JunjaMode, null, null, null),
            new KeyInput (Keys.FinalMode, null, null, null),
            new KeyInput (Keys.KanjiMode, null, null, null),
            new KeyInput (Keys.HanjaMode, null, null, null),
            new KeyInput (Keys.Escape, null, null, null),
            new KeyInput (Keys.IMEConvert, null, null, null),
            new KeyInput (Keys.IMENonconvert, null, null, null),
            new KeyInput (Keys.IMEAccept, null, null, null),
            new KeyInput (Keys.IMEAceept, null, null, null),
            new KeyInput (Keys.IMEModeChange, null, null, null),
            new KeyInput (Keys.Space, ' ', ' ', null),
            new KeyInput (Keys.Prior, null, null, null),
            new KeyInput (Keys.PageUp, null, null, null),
            new KeyInput (Keys.PageDown, null, null, null),
            new KeyInput (Keys.Next, null, null, null),
            new KeyInput (Keys.End, null, null, null),
            new KeyInput (Keys.Home, null, null, null),
            new KeyInput (Keys.Left, null, null, null),
            new KeyInput (Keys.Up, null, null, null),
            new KeyInput (Keys.Right, null, null, null),
            new KeyInput (Keys.Down, null, null, null),
            new KeyInput (Keys.Select, null, null, null),
            new KeyInput (Keys.Print, null, null, null),
            new KeyInput (Keys.Execute, null, null, null),
            new KeyInput (Keys.Snapshot, null, null, null),
            new KeyInput (Keys.PrintScreen, null, null, null),
            new KeyInput (Keys.Insert, null, null, null),
            new KeyInput (Keys.Delete, null, null, null),
            new KeyInput (Keys.Help, null, null, null),
            new KeyInput (Keys.D0, '0', '=', '}'),
            new KeyInput (Keys.D1, '1', '!', null),
            new KeyInput (Keys.D2, '2', '"', '²'),
            new KeyInput (Keys.D3, '3', '§', '³'),
            new KeyInput (Keys.D4, '4', '$', null),
            new KeyInput (Keys.D5, '5', '%', null),
            new KeyInput (Keys.D6, '6', '&', null),
            new KeyInput (Keys.D7, '7', '/', '{'),
            new KeyInput (Keys.D8, '8', '(', '['),
            new KeyInput (Keys.D9, '9', ')', ']'),
            new KeyInput (Keys.A, 'a', 'A', null),
            new KeyInput (Keys.B, 'b', 'B', null),
            new KeyInput (Keys.C, 'c', 'C', null),
            new KeyInput (Keys.D, 'd', 'D', null),
            new KeyInput (Keys.E, 'e', 'E', '€'),
            new KeyInput (Keys.F, 'f', 'F', null),
            new KeyInput (Keys.G, 'g', 'G', null),
            new KeyInput (Keys.H, 'h', 'H', null),
            new KeyInput (Keys.I, 'i', 'I', null),
            new KeyInput (Keys.J, 'j', 'J', null),
            new KeyInput (Keys.K, 'k', 'K', null),
            new KeyInput (Keys.L, 'l', 'L', null),
            new KeyInput (Keys.M, 'm', 'M', 'µ'),
            new KeyInput (Keys.N, 'n', 'N', null),
            new KeyInput (Keys.O, 'o', 'O', null),
            new KeyInput (Keys.P, 'p', 'P', null),
            new KeyInput (Keys.Q, 'q', 'Q', '@'),
            new KeyInput (Keys.R, 'r', 'R', null),
            new KeyInput (Keys.S, 's', 'S', null),
            new KeyInput (Keys.T, 't', 'T', null),
            new KeyInput (Keys.U, 'u', 'U', null),
            new KeyInput (Keys.V, 'v', 'V', null),
            new KeyInput (Keys.W, 'w', 'W', null),
            new KeyInput (Keys.X, 'x', 'X', null),
            new KeyInput (Keys.Y, 'y', 'Y', null),
            new KeyInput (Keys.Z, 'z', 'Z', null),
            new KeyInput (Keys.LWin, null, null, null),
            new KeyInput (Keys.RWin, null, null, null),
            new KeyInput (Keys.Apps, null, null, null),
            new KeyInput (Keys.Sleep, null, null, null),
            new KeyInput (Keys.NumPad0, '0', null, null),
            new KeyInput (Keys.NumPad1, '1', null, null),
            new KeyInput (Keys.NumPad2, '2', null, null),
            new KeyInput (Keys.NumPad3, '3', null, null),
            new KeyInput (Keys.NumPad4, '4', null, null),
            new KeyInput (Keys.NumPad5, '5', null, null),
            new KeyInput (Keys.NumPad6, '6', null, null),
            new KeyInput (Keys.NumPad7, '7', null, null),
            new KeyInput (Keys.NumPad8, '8', null, null),
            new KeyInput (Keys.NumPad9, '9', null, null),
            new KeyInput (Keys.Multiply, '*', '*', null),
            new KeyInput (Keys.Add, '+', '+', null),
            new KeyInput (Keys.Separator, ',', null, null),
            new KeyInput (Keys.Subtract, '-', '-', null),
            new KeyInput (Keys.Decimal, ',', ',', null),
            new KeyInput (Keys.Divide, '/', '/', null),
            new KeyInput (Keys.F1, null, null, null),
            new KeyInput (Keys.F2, null, null, null),
            new KeyInput (Keys.F3, null, null, null),
            new KeyInput (Keys.F4, null, null, null),
            new KeyInput (Keys.F5, null, null, null),
            new KeyInput (Keys.F6, null, null, null),
            new KeyInput (Keys.F7, null, null, null),
            new KeyInput (Keys.F8, null, null, null),
            new KeyInput (Keys.F9, null, null, null),
            new KeyInput (Keys.F10, null, null, null),
            new KeyInput (Keys.F11, null, null, null),
            new KeyInput (Keys.F12, null, null, null),
            new KeyInput (Keys.F13, null, null, null),
            new KeyInput (Keys.F14, null, null, null),
            new KeyInput (Keys.F15, null, null, null),
            new KeyInput (Keys.F16, null, null, null),
            new KeyInput (Keys.F17, null, null, null),
            new KeyInput (Keys.F18, null, null, null),
            new KeyInput (Keys.F19, null, null, null),
            new KeyInput (Keys.F20, null, null, null),
            new KeyInput (Keys.F21, null, null, null),
            new KeyInput (Keys.F22, null, null, null),
            new KeyInput (Keys.F23, null, null, null),
            new KeyInput (Keys.F24, null, null, null),
            new KeyInput (Keys.NumLock, null, null, null),
            new KeyInput (Keys.Scroll, null, null, null),
            new KeyInput (Keys.LShiftKey, null, null, null),
            new KeyInput (Keys.RShiftKey, null, null, null),
            new KeyInput (Keys.LControlKey, null, null, null),
            new KeyInput (Keys.RControlKey, null, null, null),
            new KeyInput (Keys.LMenu, null, null, null),
            new KeyInput (Keys.RMenu, null, null, null),
            new KeyInput (Keys.BrowserBack, null, null, null),
            new KeyInput (Keys.BrowserForward, null, null, null),
            new KeyInput (Keys.BrowserRefresh, null, null, null),
            new KeyInput (Keys.BrowserStop, null, null, null),
            new KeyInput (Keys.BrowserSearch, null, null, null),
            new KeyInput (Keys.BrowserFavorites, null, null, null),
            new KeyInput (Keys.BrowserHome, null, null, null),
            new KeyInput (Keys.VolumeMute, null, null, null),
            new KeyInput (Keys.VolumeDown, null, null, null),
            new KeyInput (Keys.VolumeUp, null, null, null),
            new KeyInput (Keys.MediaNextTrack, null, null, null),
            new KeyInput (Keys.MediaPreviousTrack, null, null, null),
            new KeyInput (Keys.MediaStop, null, null, null),
            new KeyInput (Keys.MediaPlayPause, null, null, null),
            new KeyInput (Keys.LaunchMail, null, null, null),
            new KeyInput (Keys.SelectMedia, null, null, null),
            new KeyInput (Keys.LaunchApplication1, null, null, null),
            new KeyInput (Keys.LaunchApplication2, null, null, null),
            new KeyInput (Keys.OemSemicolon, null, null, null),
            new KeyInput (Keys.Oem1, 'ü', 'Ü', null),
            new KeyInput (Keys.Oemplus, '+', '*', '~'),
            new KeyInput (Keys.Oemcomma, ',', ';', null),
            new KeyInput (Keys.OemMinus, '-', '_', null),
            new KeyInput (Keys.OemPeriod, '.', ':', null),
            new KeyInput (Keys.Oem2, '#', '\'', null),
            new KeyInput (Keys.OemQuestion, null, null, null),
            new KeyInput (Keys.Oem3, 'ö', 'Ö', null),
            new KeyInput (Keys.Oemtilde, null, null, null),
            new KeyInput (Keys.Oem4, 'ß', '?', '\\'),
            new KeyInput (Keys.OemOpenBrackets, null, null, null),
            new KeyInput (Keys.OemPipe, null, null, null),
            new KeyInput (Keys.Oem5, '^', '°', null),
            new KeyInput (Keys.OemCloseBrackets, null, null, null),
            new KeyInput (Keys.Oem6, '´', '`', null),
            new KeyInput (Keys.OemQuotes, null, null, null),
            new KeyInput (Keys.Oem7, 'ä', 'Ä', null),
            new KeyInput (Keys.Oem8, null, null, null),
            new KeyInput (Keys.Oem102, '<', '>', '|'),
            new KeyInput (Keys.OemBackslash, null, null, null),
            new KeyInput (Keys.ProcessKey, null, null, null),
            new KeyInput (Keys.Packet, null, null, null),
            new KeyInput (Keys.Attn, null, null, null),
            new KeyInput (Keys.Crsel, null, null, null),
            new KeyInput (Keys.Exsel, null, null, null),
            new KeyInput (Keys.EraseEof, null, null, null),
            new KeyInput (Keys.Play, null, null, null),
            new KeyInput (Keys.Zoom, null, null, null),
            new KeyInput (Keys.NoName, null, null, null),
            new KeyInput (Keys.Pa1, null, null, null),
            new KeyInput (Keys.OemClear, null, null, null),
            new KeyInput (Keys.KeyCode, null, null, null),
            new KeyInput (Keys.Shift, null, null, null),
            new KeyInput (Keys.Control, null, null, null),
            new KeyInput (Keys.Alt, null, null, null),
            new KeyInput (Keys.Modifiers, null, null, null),
        };
    }
}